apiVersion: apps/v1
kind: Deployment
metadata:
  name: henriquefagundes-american-predictor
  labels:
    app: henriquefagundes-american-predictor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: henriquefagundes-american-predictor
  template:
    metadata:
      labels:
        app: henriquefagundes-american-predictor
    spec:
      containers:
      - name: predict-american-tweets
        image: henriquef/predict_american_tweets:0.2
        ports:
        - containerPort: 5013
